### ISSUE TITLE
Throwing a mean ass error

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TF-WorldEdit#18]
We are getting some major error, its not after a command and I havent really looked at it, so here it is:

`:[21:46:51 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit commandjava.lang.RuntimeException: com.sk89q.worldedit.MaxChangedBlocksException
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76)
	at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:84)
	at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:46)
	at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52)
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270)
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242)
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302)
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137)
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716)
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sk89q.worldedit.MaxChangedBlocksException
	at com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:83)
	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:503)
	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:546)
	at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53)
	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57)
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74)
	... 29 more
`

**Comment by AvalancheYT** [comment]
Since no-one have confirm it, I have found out what causing these errors - ```I have confirm the bug, the error occurs when the worldedit have reached to your max limit.
The way to solve it is to set your limit to -1 (Unlimited) //limit -1```
